### ISSUE TITLE
Throttle Notifications

### ISSUE THREAD

**Issue by Kamleshpa** [linkedin/Burrow#233]
Is there a way to throttle the notifications for given time? For example when a consumer goes bad then i keep getting slack notification every 5 secs. I wish to have some throttle time (in mins) after the 1st error notification is sent. That way I can avoid flooding my slack channel.

I am happy to add this feature if it doesn't exists.

**Comment by rconn01** [comment]
+ 1 I am also looking for this feature. It would good if there was a way to limit how many slack notifications get sent out. Also it would be good if there was way to get close notifications without subscribing to all OK messages. Looking at the code I don't see a way to achieve this. It looks like the slack notifier can only register to specific notification levels.

**Comment by xannz** [comment]
+1 from me. Is this being worked on?

**Comment by toddpalino** [comment]
It looks like the Slack notifier just uses the main notify interval config for this. It should, at the very least, have its own interval configuration. However, this also governs how often it checks to see if there's anything to report. It sounds like what we need are two different values here - one for how frequently to check for problems, and one for how frequently to report those problems. I'll work on this as part of 1.0

**Comment by toddpalino** [comment]
Resolved by 1.0 rewrite

**Comment by adomenech73** [comment]
Hi @toddpalino, so is it possible now to have the reporting interval set to 0 for notification only in case when there is a status toggle/change, rather than on every interval seconds??

**Comment by pawanrawal** [comment]
To answer your question @adomenech73, no that behavior is still not possible. See https://github.com/linkedin/Burrow/commit/f3659d121a36fb9ebfd2519c024a132260323bb0, `send-interval` only controls how often a notification is sent.
