### ISSUE TITLE
Just doesn't start, no errors

### ISSUE THREAD

**Issue by mbonaci** [linkedin/Burrow#29]
![image](https://cloud.githubusercontent.com/assets/497926/10590574/b3fb9718-76b1-11e5-8815-246bd746629a.png)
```
[general]
logdir=log
logconfig=config/logging.cfg
pidfile=burrow.pid
client-id=burrow-lagchecker
group-blacklist=^(console-consumer-|python-kafka-consumer-).*$

[zookeeper]
hostname=dockerhost
port=2181
timeout=6
lock-path=/burrow/notifier

[kafka "local"]
broker=dockerhost
broker-port=10251
zookeeper=dockerhost
zookeeper-port=2181
zookeeper-path=/
offsets-topic=__consumer_offsets

[tickers]
broker-offsets=60

[lagcheck]
intervals=10
expire-group=604800

[httpserver]
server=on
port=8000

[smtp]
server=mailserver.example.com
port=25
from=burrow-noreply@example.com
template=config/default-email.tmpl

[email "bofh@example.com"]
group=local,critical-consumer-group
group=local,other-consumer-group
interval=60

[httpnotifier]
url=http://notification.server.example.com:9000/v1/alert
interval=60
extra=app=burrow
extra=tier=STG
template-post=config/default-http-post.tmpl
template-delete=config/default-http-delete.tmpl
```

**Comment by toddpalino** [comment]
This really isn't enough information to diagnose any problems. I'll need to see at least the logs generated in the log directory

**Comment by viswamitra** [comment]
Hi, 
I have faced a similar issue. Here is the log appended. I'm assuming @mbonaci also has a similar issue. 

```code```
Started Burrow at December 6, 2015 at 12:58am (IST)
1449343738608363637 [Info] Starting Zookeeper client
1449343738609420990 [Info] Starting Offsets Storage module
1449343738609444513 [Info] Starting HTTP server
1449343738610394436 [Info] Starting Zookeeper client for cluster local
1449343738617678987 [Debug] Add ZK consumer group <consumer-group-name> to cluster local
1449343738617706858 [Info] Starting Kafka client for cluster local
1449343738622231820 [Error] Cannot fetch offsets from broker 0: dial tcp: too many colons in address <ipv6_address_of_the_broker>:9092
1449343738622262083 [Info] Starting consumers for 50 partitions of __consumer_offsets in cluster local
1449343738623432214 [Critical] Cannot start Kafka client for cluster local: dial tcp: too many colons in address <ipv6_address_of_the_broker>:9092
Burrow failed at December 6, 2015 at 12:58am (IST)

**Comment by toddpalino** [comment]
Thanks for the detail, @viswamitra. This is a problem with the handling of IPv6 addresses. One way to handle it is to provide the addresses to the dial routine in golang as "[host]:port" (with the host in square brackets). As this is done deeper down in the sarama library that is used as the Kafka client, there's a question as to whether the patch should be made to Burrow or to sarama.

I'm going to start looking at the ZK client to see how it handles it (if it does)

**Comment by toddpalino** [comment]
I've pushed a fix to config.go for the IPv6 address handling. I've confirmed that it works for hostnames and IPv4 addresses, but I don't have an environment for testing IPv6 right now. I'd appreciate it if you could pull master and see if it resolves your issue.

**Comment by viswamitra** [comment]
Hi @toddpalino , 
I pulled the code and checked with some ipv4 addresses, localhost and 127.0.0.1 still get the same error message as before. Have you checked with localhost and loopback addresses?

**Comment by toddpalino** [comment]
Yes, I have, and I have no problems with it. I have done this with both IPv4 and IPv6 loopback. I suspect you may have an issue with your configuration that is causing this problem. Can you please paste the lines defining your Kafka cluster?

**Comment by Bongsakorn** [comment]
I got another error like this

[CRITICAL] Cannot start Kafka client for cluster local: kafka server: Request was for a topic or partition that does not exist on this broker.

I set zookeeper path to "/" and data in zookeeper is [consumers, controller_epoch, admin, zookeeper, brokers]

**Comment by toddpalino** [comment]
OK, I'm closing this issue out as there has been no update in over 2 months.

@Bongsakorn, your issue is unrelated. It sounds like the __consumer_offsets topic has not been created yet, which should happen automatically. Please make sure you are running a recent version of Kafka, and you have at least one consumer running and committing offsets to Kafka. It also looks from your ZK information that the cluster is not currently running. There should be a controller znode if it was running.

If you continue to have problems, please open a separate issue.
