### ISSUE TITLE
Any plan to support kafka 1.0?

### ISSUE THREAD

**Issue by jiming** [linkedin/Burrow#348]
Thanks a lot!

**Comment by toddpalino** [comment]
That will be up to Sarama, which is the underlying client we use.

**Comment by brettrann** [comment]
1.0 was added to sarama in 1.15.0
https://github.com/Shopify/sarama/blob/v1.15.0/utils.go#L152

And 1.15.0 is already referenced in master in burrow also.  There were no actual client changes made to sarama for 1.0 (just support for the version string) and AFAIK no relevant client changes in kafka, so it's a bit of a moot point over 0.11

build burrow from master, or set this https://github.com/linkedin/Burrow/blob/master/Gopkg.toml#L3 and try it out. :)

**Comment by brettrann** [comment]
papertrail: PR for 1.0 being added to burrow: https://github.com/linkedin/Burrow/pull/306

**Comment by toddpalino** [comment]
Thanks. Kinda silly when I don't remember the PR I merged :)

This will be in the next release, which I anticipate will be cut pretty soon to pick up a few bug fixes.

**Comment by ankur1511** [comment]
Sarama has already added kafka version 1.1.0 in its version 1.16.0. But burrow is still not supporting kafka version 1.0.1 and above. are you planning to make some chan
<img width="917" alt="screen shot 2018-04-09 at 4 46 55 pm" src="https://user-images.githubusercontent.com/17586366/38495018-b0461bee-3c15-11e8-9f57-bf3174cb6785.png">
ges?

**Comment by balarampuli** [comment]
what are the supported kafka versions for latest burrow and burrowui?

**Comment by brettrann** [comment]
this ticket has been closed.  Please create new ones instead of necroing :)

To address your question:
Sarama 1.16.0 does not support 1.1.0. They only have that in master. They work on a 2 month release cycle so it shouldn't be long.
Sarama hasn't added version string support for 1.0.1 either, at all.
